import React from 'react'

const Pi = () => {
    return (
        <div className='pi px-4 py-5'>
            <p className='fs-12'>PRODUCT INFORMATION FOR HEALTHCARE PROFESSIONALS</p>
            <p className='fs-12'>▼ This medicinal product is subject to additional monitoring. Reporting suspected adverse reactions after authorisation of the medicinal product is important. It allows continued monitoring of the benefit/risk balance of the medicinal product. Healthcare professionals are asked to report any suspected adverse reactions via the national reporting systems and to DrugSafety.Global@glpg.com.</p>
            <p className='fs-12'><strong>Abbreviated Summary of Product Characteristics: Jyseleca® (filgotinib),</strong> 100 mg or 200 mg film-coated tablets.</p>
            <p className='fs-12'><strong>Indications:</strong> Treatment of moderate to severe rheumatoid arthritis in adults who have had an inadequate response to, or who are intolerant to, one or more disease-modifying anti-rheumatic drugs (DMARDs). Can be used as monotherapy or in combination with methotrexate.</p>
            <p className='fs-12'><strong>Dosage:</strong> Treatment should be initiated by a physician experienced in the treatment of rheumatoid arthritis. The tablets should be swallowed whole. For guidance on laboratory monitoring and dose initiation or discontinuation, see the Summary of Product Characteristics. Treatment should be discontinued if a patient develops a serious infection until the infection is under control.<u>Adults:</u>  200 mg once daily. <u>Elderly ≥75 years:</u> Recommended starting dose: 100 mg once daily. <u>Moderate or severe renal impairment (CrCl 15 to 60 mL/min):</u> 100
                mg once daily. <u>End-stage renal disease (CrCl 15 mL/min):</u> Filgotinib has not been studied and is therefore not recommended. <u>Severe hepatic impairment (Child-Pugh C):</u> Filgotinib has not been studied and is therefore not recommended. Children 18 years: The safety and
                efficacy of filgotinib have not yet been established. No data available.</p>
            <p className='fs-12'><strong>Contraindications:</strong> Hypersensitivity to the active substance or to any of the excipients, active tuberculosis (TB), active serious infections, pregnancy.</p>
            <p className='fs-12'><strong>Warnings and precautions:</strong> <u>Immunosuppressants:</u> Combination with other potent immunosuppressants such as azathioprine, ciclosporin, tacrolimus, biological DMARDs or other Janus kinase (JAK) inhibitors is not recommended. <u>Infections,</u> including severe infections (most commonly pneumonia), have been reported. Patients should be closely monitored for the development of signs and symptoms of infection during and after treatment with filgotinib. Elderly ≥75 years: Caution should be exercised due to higher incidence of serious infections. Tuberculosis: Patients should be screened for TB before initiating filgotinib. Filgotinib must not be used during active TB. In latent TB, standard antimycobacterial therapy should be given before filgotinib administration. <u>Viral reactivation</u> (including herpesvirus reactivation) has been reported in clinical trials. If the patient develops shingles, treatment should be temporarily withheld until the episode is resolved. <u>Malignancy:</u> Malignancies have been observed in clinical trials with filgotinib. Risks and benefits should be considered before initiating treatment for known malignancy other than well-treated non-melanoma skin cancer (NMSC), or when considering continuing treatment in patients who develop a malignancy. Patients at increased risk of skin cancer should have regular skin examinations. <u>Haematological abnormalities:</u>x Treatment should not be initiated or should be discontinued temporarily in patients with absolute neutrophil count (ANC) 1 x 109 cells/L, absolute lymphocyte count (ALC) 0.5 x 109 cells/L or haemoglobin 8 g/dL observed during routine treatment. <u>Vaccinations:</u> Use of live vaccines during/immediately before treatment with filgotinib is not recommended. <u>Cardiovascular risk:</u> Risk factors (eg, hypertension, hyperlipidaemia) should be treated as part of normal treatment. <u>Venous thromboembolism:</u> JAK inhibitors should be used with caution in risk factors for DVT/PE or in connection with surgery and prolonged immobilisation. In case of clinical signs of DVT/PE, treatment should be discontinued and the patient evaluated immediately, followed by appropriate treatment.</p>
            <p className='fs-12'><strong>Interactions:</strong> <u>P-gp or BCRP inhibition:</u> Caution should be exercised when administering substrates with a narrow therapeutic index concomitantly with filgotinib.</p>
            <p className='fs-12'><strong>Side effects:</strong> <u>Common:</u> Urinary tract infection, upper respiratory tract infection, dizziness, nausea.</p>
            <p className='fs-12'><strong>Overdose:</strong> In case of overdose, the patient should be monitored for signs and symptoms of side effects. <u>Treatment:</u> General supportive measures, including monitoring of vital signs as well as observation of the patient’s clinical status. It is not known if filgotinib can be removed by dialysis.</p>
            <p className='fs-12'><strong>Pregnancy:</strong> Filgotinib is contraindicated during pregnancy. Women of childbearing potential must use effective contraception during treatment and for at least 1 week after stopping treatment.</p>
            <p className='fs-12'><strong>Breastfeeding:</strong> Jyseleca must not be used during breastfeeding.</p>
            <p className='fs-12'><strong>Fertility:</strong> The potential risk of reduced fertility/infertility should be discussed with male patients before initiating treatment.</p>
            <p className='fs-12'><strong>Driving/operating machinery:</strong> Filgotinib has no or negligible influence on the ability to drive and operate machinery. However, patients should be informed that dizziness has been reported during treatment with Jyseleca.</p>
            <p className='fs-12'><strong>Pack sizes:</strong> 30 and 3 × 30 tablets.</p>
            <p className='fs-12'><strong>Price:</strong> See current medicine prices at <a href="www.medicinpriser.dk">www.medicinpriser.dk.</a></p>
            <p className='fs-12'><strong>Grant status:</strong> Not eligible.</p>
            <p className='fs-12'><strong>Delivery:</strong> NBS (may only be dispensed to hospitals or on the prescription of specific specialists).</p>
            <p className='fs-12'><strong>Marketing authorisation number:</strong> EU/1/20/1480/003, EU/1/20/1480/004</p>
            <p className='fs-12'><strong>Marketing authorisation holder:</strong> Galapagos NV, Belgium.</p>
            <p className='fs-12'><strong>The product information is abbreviated in relation to the product summary approved by the European Medicines Agency (EMA) dated 16.12.2021.</strong> A complete product summary can be requested from the marketing authorisation holder or the Danish representative: <strong>Galapagos, tel. +800 7878 1345</strong> or viewed on EMA’s website.</p>
            <p className='fs-12'><strong>PLEASE READ THE SUMMARY OF PRODUCT CHARACTERISTICS BEFORE PRESCRIBING, IN PARTICULAR WITH REGARD TO SIDE EFFECTS, WARNINGS, AND CONTRAINDICATIONS.</strong></p>
        </div>
    )
}

export default Pi